#!/usr/bin/env bash

# Copy this hook in .git/hooks if you want the min files to be rebuilt
# whenever HEAD is pointed to a different branch with source code changes
YELLOW='\033[0;33m'
RESET_COLOR='\033[0m'

CHANGES_TO_SRC_PRESENT=$(git diff @{-1} HEAD --exit-code --name-only -- *.scss)

if [ -n "$CHANGES_TO_SRC_PRESENT" ]
then
  echo -e "${YELLOW}Changes in *.scss files detected, rebuilding dist files...${RESET_COLOR}"
  npx gulp sass
fi
